global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.84.47:8403']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.84.47:8405']
        labels:
          instance: 'node_exporter'
  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['192.168.84.47:8408']
        labels:
          instance: 'redis_exporter'
  - job_name: 'mysql_exporter'
    static_configs:
      - targets: ['192.168.84.47:8409']
        labels:
          instance: 'mysql_exporter'
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.84.47:8407']
        labels:
          instance: 'cadvisor'

  - job_name: 'platform-server-system-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.108.151:8201']
        labels:
          instance: 'platform-server-system'
  - job_name: 'platform-server-auth-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.108.151:8101']
        labels:
          instance: 'platform-auth'
rule_files:
  - 'memory_over.yml'
  - 'server_down.yml'
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["192.168.84.47:8406"]
