apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-client-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: cloudkube.com/nfs # 名称可自定义
            - name: NFS_SERVER
              value: 192.168.84.48 # NFS服务器IP
            - name: NFS_PATH
              value: /nfs/nfs-share # NFS目录
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.84.48 # NFS服务器IP
            path: /nfs/nfs-share # NFS目录