apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage # StorageClass名称，可自定义
provisioner: cloudkube.com/nfs # 和client-provisioner-deployment.yml里定义的一致
parameters:
  archiveOnDelete: "false"