route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 5m
  receiver: 'wechat'

receivers:
  - name: 'wechat'
    wechat_configs:
      - corp_id: 'wwd1c11363283e02bc'
        to_party: '1'
        agent_id: '1000002'
        api_secret: '0Fqr5ErRBYYy75_dM08gcS27Oq-FDx2NmIzNudOSOwE'