route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 5m
  receiver: 'wechat'

receivers:
  - name: 'wechat'
    wechat_configs:
      - corp_id: '123456'
        to_party: '1'
        agent_id: '1000002'
        api_secret: '123456'