global:
  smtp_smarthost: 'smtp.qq.com:465'
  smtp_from: '764471698@qq.com'
  smtp_auth_username: '764471698'
  smtp_auth_password: '123456'
  smtp_require_tls: false

#templates:
#  - '/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 5m
  receiver: 'default-receiver'

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'chenwenhua666@aliyun.com'
        send_resolved: true