{
 "title": "MySQL 监控面板",
 "description": "MySQL数据库监控",
 "tags": [
  "MySQL",
  "Prometheus",
  "mysqld-exporter"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_up, instance)"
   }
  ]
 },
 "panels": [
  { "title": "总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MySQL 正常运行时间",
   "type": "singlestat",
   "description": "mysqld 服务器进程最后一次重启的时间。",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_uptime{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "当前的 QPS",
   "type": "singlestat",
   "description": "**Current QPS**\n\n根据 MySQL 的 ``SHOW STATUS`` 命令所返回的查询结果计算，它是服务器在最后一秒内执行的查询语句数。\n\n这个值包括存储过程当中所执行的 SQL 语句数量，与 ``Questions`` 所统计的结果不同，他不包含 ``COM_PING `` 与 ``COM_STATISTICS `` 命令返回的结果。",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mysql_global_status_queries{instance=\"$host\"}[$interval]) or irate(mysql_global_status_queries{instance=\"$host\"}[5m])"
    }
   ]
  },
  {
   "title": "InnoDB 缓冲池大小",
   "type": "singlestat",
   "description": "InnoDB 维护了一个缓冲池，用于在内存当中进行数据缓存与索引。\n\n了解 InnoDB 缓冲池是如何工作地，就可以利用它将频繁访问的数据存储在内存当中。这也是 MySQL 性能调优的重要一个技巧。\n\n最终的目的就是缓存结果，在大多数情况下，他的值应该是主机内存的 60% ~ 90% 之间。",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_innodb_buffer_pool_size{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Buffer Pool Size of Total RAM",
   "type": "singlestat",
   "description": "**InnoDB Buffer Pool Size % of Total RAM**\n\nInnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.  Knowing how the InnoDB buffer pool works, and taking advantage of it to keep frequently accessed data in memory, is one of the most important aspects of MySQL tuning. The goal is to keep the working set in memory. In most cases, this should be between 60%-90% of available memory on a dedicated database host, but depends on many factors.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(mysql_global_variables_innodb_buffer_pool_size{instance=\"$host\"} * 100) / on (instance) node_memory_MemTotal_bytes{instance=\"$host\"}"
    }
   ]
  },
  { "title": "连接数", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "MySQL 连接数统计",
   "type": "graph",
   "description": "注释\n\nMySQL 默认的最大连接数为 151，增加这个值的话，会导致 mysqld 所需要的文件描述符数量。当文件描述符剩余不可用的时候，mysqld 会自动降低最大连接数。\n\n实质上 mysqld 允许 (最大连接数 + 1) 个连接，额外的 1 个连接是保留给 root 用户使用的。\n\n服务器最大连接记录是 mysqld 自启动以来同时最大使用的连接数记录。(不论成功与否)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max(max_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[$interval])  or mysql_global_status_threads_connected{instance=\"$host\"} )",
     "legendFormat": "当前连接数"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_max_used_connections{instance=\"$host\"}",
     "legendFormat": "服务器最大连接记录"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_max_connections{instance=\"$host\"}",
     "legendFormat": "最大连接数"
    }
   ]
  },
  {
   "title": "MySQL 活动的线程数",
   "type": "graph",
   "description": "``已连接的线程数`` 是打开的连接数，而 ``运行中的线程数`` 则是未休眠的线程数统计。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[5m])",
     "legendFormat": "已连接的线程数"
    },
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_global_status_threads_running{instance=\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_running{instance=\"$host\"}[5m])",
     "legendFormat": "运行中的线程数"
    },
    {
     "expr": "avg_over_time(mysql_global_status_threads_running{instance=\"$host\"}[$interval]) or \navg_over_time(mysql_global_status_threads_running{instance=\"$host\"}[5m])",
     "legendFormat": "平均运行的线程数"
    }
   ]
  },
  { "title": "表锁定", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "MySQL 查询数",
   "type": "graph",
   "description": "MySQL 服务器执行的查询语句统计，这只包含客户端发送的查询请求，而不包括存储过程当中执行的语句数。\n\n该统计与 QPS 统计的信息不同，此图表不计算以下命令:\n* ``COM_PING``\n* ``COM_STATISTICS``\n* ``COM_STMT_PREPARE``\n* ``COM_STMT_CLOSE``\n* ``COM_STMT_RESET``",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_questions{instance=\"$host\"}[$interval]) or irate(mysql_global_status_questions{instance=\"$host\"}[5m])",
     "legendFormat": "查询数"
    }
   ]
  },
  {
   "title": "MySQL 线程缓存",
   "type": "graph",
   "description": "``The thread_cache_size`` 变量用于配置服务器应该缓存多少个线程来进行复用。当客户端断开连接的时候，如果线程缓存池没有满的话则将该线程放入线程缓存池当中。\n\n它在 MySQL 5.6.8 以上版本会自动调整大小 (上限为 100)。\n\n如果线程池有可用线程的话，他会优先从缓存池当中拿取线程处理。并且只有在线程缓存池当中没有可用线程的时候才会创建新的线程。\n\n* *Threads_created*: 为处理连接请求而创建的线程数量。\n* *Threads_cached*: 已缓存的线程数量。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_thread_cache_size{instance=\"$host\"}",
     "legendFormat": "线程缓存池大小"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_threads_cached{instance=\"$host\"}",
     "legendFormat": "已经缓存的线程"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_threads_created{instance=\"$host\"}[$interval]) or irate(mysql_global_status_threads_created{instance=\"$host\"}[5m])",
     "legendFormat": "已创建的线程"
    }
   ]
  },
  { "title": "临时对象", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "MySQL 临时对象",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_created_tmp_tables{instance=\"$host\"}[$interval]) or irate(mysql_global_status_created_tmp_tables{instance=\"$host\"}[5m])",
     "legendFormat": "创建的临时表"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_created_tmp_disk_tables{instance=\"$host\"}[$interval]) or irate(mysql_global_status_created_tmp_disk_tables{instance=\"$host\"}[5m])",
     "legendFormat": "创建到硬盘的临时表"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_created_tmp_files{instance=\"$host\"}[$interval]) or irate(mysql_global_status_created_tmp_files{instance=\"$host\"}[5m])",
     "legendFormat": "创建临时文件"
    }
   ]
  },
  {
   "title": "MySQL Select 查询类型",
   "type": "graph",
   "description": "基于索引进行 Select 比全表扫描更加有效，在这个图表当中看到的是未使用索引导致的 Select 查询统计。\n\n* ***Select Scan*** 是导致进行全表扫描的查询语句数量，其表中的所有数据都必须被读取和丢弃，才能够返回。\n* ***Select Range*** 是使用一个范围扫描的查询数统计，这意味着 MySQL 扫描了给定范围的所有行。\n* ***Select Full Join*** 是连接查询时未使用索引的查询数统计，这通常会对性能造成重大影响。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_full_join{instance=\"$host\"}[$interval]) or irate(mysql_global_status_select_full_join{instance=\"$host\"}[5m])",
     "legendFormat": "Select Full Join"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_full_range_join{instance=\"$host\"}[$interval]) or irate(mysql_global_status_select_full_range_join{instance=\"$host\"}[5m])",
     "legendFormat": "Select Full Range Join"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_range{instance=\"$host\"}[$interval]) or irate(mysql_global_status_select_range{instance=\"$host\"}[5m])",
     "legendFormat": "Select Range"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_range_check{instance=\"$host\"}[$interval]) or irate(mysql_global_status_select_range_check{instance=\"$host\"}[5m])",
     "legendFormat": "Select Range Check"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_scan{instance=\"$host\"}[$interval]) or irate(mysql_global_status_select_scan{instance=\"$host\"}[5m])",
     "legendFormat": "Select Scan"
    }
   ]
  },
  { "title": "排序", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "MySQL 排序",
   "type": "graph",
   "description": "由于查询结构、顺序等要求，MySQL 会在返回数据前针对数据行进行排序。\n\n这张图还显示了什么时候排序必须扫描整个表，或者需要扫描指定的范围才能够返回结果，而这些结果通常不能够根据索引来进行排序。",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_rows{instance=\"$host\"}[$interval]) or irate(mysql_global_status_sort_rows{instance=\"$host\"}[5m])",
     "legendFormat": "Sort Rows"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_range{instance=\"$host\"}[$interval]) or irate(mysql_global_status_sort_range{instance=\"$host\"}[5m])",
     "legendFormat": "Sort Range"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_merge_passes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_sort_merge_passes{instance=\"$host\"}[5m])",
     "legendFormat": "Sort Merge Passes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_scan{instance=\"$host\"}[$interval]) or irate(mysql_global_status_sort_scan{instance=\"$host\"}[5m])",
     "legendFormat": "Sort Scan"
    }
   ]
  },
  {
   "title": "MySQL 慢查询",
   "type": "graph",
   "description": "慢查询的定义是比 ``long_query_time`` 所设置的值还要慢的查询，例如你把 ``long_query_time`` 的值设置为 3 ，那么需要超过 3 秒之后才能够完成的查询就是慢查询，这些查询会被统计到本图当中。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_slow_queries{instance=\"$host\"}[$interval]) or irate(mysql_global_status_slow_queries{instance=\"$host\"}[5m])",
     "legendFormat": "慢查询语句"
    }
   ]
  },
  { "title": "异常信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "MySQL 异常中断的连接",
   "type": "graph",
   "description": "当某个客户端连接到 MySQL 时，连接异常中断，而 MySQL 会将该信息保存在异常表当中。\n\n如果没有连接异常的数量到达 ``max_connect_errors`` 的值，mysqld 将会假定有错误并且进一步阻止客户的进一步连接。如果要允许该客户端再次连接，需要执行 ``FLUSH HOSTS`` 命令。",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_aborted_connects{instance=\"$host\"}[$interval]) or irate(mysql_global_status_aborted_connects{instance=\"$host\"}[5m])",
     "legendFormat": "异常中断的客户端 (尝试连接)"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_aborted_clients{instance=\"$host\"}[$interval]) or irate(mysql_global_status_aborted_clients{instance=\"$host\"}[5m])",
     "legendFormat": "异常中断的客户端 (超时)"
    }
   ]
  },
  {
   "title": "MySQL 表锁定",
   "type": "graph",
   "description": "MySQL 会因为不同的原因而使用各种锁，在这个统计图当中我们可以看到 MySQL 从存储引擎当中请求了多少个表级锁。\n\n在 InnoDB 作为存储引擎的情况下，很多时候锁其实是行锁，只会在某些特定的情况下，才会是表级锁。\n\n比较存货的锁与锁等待是非常有用的，如果锁等待正在上升，则表明您的锁有争用。否则的话，锁的波动是很正常的活动。",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_table_locks_immediate{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_locks_immediate{instance=\"$host\"}[5m])",
     "legendFormat": "锁"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_table_locks_waited{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_locks_waited{instance=\"$host\"}[5m])",
     "legendFormat": "锁等待"
    }
   ]
  },
  { "title": "网络", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "MySQL 网络流量",
   "type": "graph",
   "description": "在这个统计图内部我们可以看到 MySQL 产生了多少网络流量。\n\n* 出站流量是 MySQL 发送的网络流量。\n* 入站流量是 MySQL 接收的网络流量。",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_bytes_received{instance=\"$host\"}[$interval]) or irate(mysql_global_status_bytes_received{instance=\"$host\"}[5m])",
     "legendFormat": "入站流量"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_bytes_sent{instance=\"$host\"}[$interval]) or irate(mysql_global_status_bytes_sent{instance=\"$host\"}[5m])",
     "legendFormat": "出站流量"
    }
   ]
  },
  {
   "title": "MySQL 每小时的网络流量统计",
   "type": "graph",
   "description": "在这里你可以看到 MySQL 每小时生成了多少流量，并且通过柱状图你可以很直白的比较 MySQL 发送与接收的数据。",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_bytes_received{instance=\"$host\"}[1h])",
     "legendFormat": "接收的数据"
    },
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_bytes_sent{instance=\"$host\"}[1h])",
     "legendFormat": "发送的数据"
    }
   ]
  },
  { "title": "内存", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "MySQL 内部内存使用总览",
   "type": "graph",
   "description": "***系统内存***: 整个系统总的内存。\\\n***InnoDB 缓冲池数据***: InnoDB 维护了一个缓冲池的内存区域，用于在内存中缓存数据与索引。\\\n***TokuDB 缓存***: 与 InnoDB 缓冲池相似，TokuDB 会为自己缓存分配 50 % 的内存。\\\n***索引缓冲区***: MYISAM 表的索引块缓冲区大小，由所有线程共享，其 ``key_buffer_size`` 参数是用于配置其缓冲区大小的。。\\\n***自适应哈希索引***: 当 InnoDB 注意到某些索引值被非常频繁地访问时，它会在 B-Tree 索引之上的内存中为它们构建哈希索引。\\\n ***查询缓存***: 查询缓存存储 SELECT 语句与对应的查询结果。查询缓存存在巨大的可伸缩性问题，因为只有一个线程可以同时在查询缓存中执行操作。\\\n***InnoDB 字典***: 数据字典是 InnoDB 的内部表。 InnoDB 将数据字典存储在磁盘上，并在服务器运行时加载到内存中。\\\n***InnoDB 日志缓冲区***: MySQL InnoDB日志缓冲区允许事务运行，而无需在事务提交之前将日志写入磁盘。",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$host\"}",
     "legendFormat": "System Memory"
    },
    {
     "expr": "mysql_global_status_innodb_page_size{instance=\"$host\"} * on (instance) mysql_global_status_buffer_pool_pages{instance=\"$host\",state=\"data\"}",
     "legendFormat": "InnoDB 缓冲池数据"
    },
    {
     "expr": "mysql_global_variables_innodb_log_buffer_size{instance=\"$host\"}",
     "legendFormat": "InnoDB 日志缓冲区"
    },
    {
     "expr": "mysql_global_variables_innodb_additional_mem_pool_size{instance=\"$host\"}",
     "legendFormat": "InnoDB Additional Memory Pool Size"
    },
    {
     "expr": "mysql_global_status_innodb_mem_dictionary{instance=\"$host\"}",
     "legendFormat": "InnoDB 字典"
    },
    {
     "expr": "mysql_global_variables_key_buffer_size{instance=\"$host\"}",
     "legendFormat": "索引缓冲区"
    },
    {
     "expr": "mysql_global_variables_query_cache_size{instance=\"$host\"}",
     "legendFormat": "查询缓存"
    },
    {
     "expr": "mysql_global_status_innodb_mem_adaptive_hash{instance=\"$host\"}",
     "legendFormat": "自适应哈希索引"
    },
    {
     "expr": "mysql_global_variables_tokudb_cache_size{instance=\"$host\"}",
     "legendFormat": "TokuDB 缓存"
    }
   ]
  },
  { "title": "MySQL 内部统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "执行命令排行",
   "type": "graph",
   "description": "Com_{{xxx}} 用于表示 xxx 命令执行的次数。每种类型的语句都会有一个状态变量，例如 ``Com_delete`` 与 ``Com_update ``。\n\n而 ``Com_delete_multi`` 则与 ``Com_update_multi`` 类似，只是他们两个是用于多表的语法。",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, rate(mysql_global_status_commands_total{instance=\"$host\"}[$interval])>0) or topk(5, irate(mysql_global_status_commands_total{instance=\"$host\"}[5m])>0)",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  },
  {
   "title": "每小时执行频率最高的命令",
   "type": "graph",
   "description": "Com_{{xxx}} 用于表示 xxx 命令执行的次数。每种类型的语句都会有一个状态变量，例如 ``Com_delete`` 与 ``Com_update ``。\n\n而 ``Com_delete_multi`` 则与 ``Com_update_multi`` 类似，只是他们两个是用于多表的语法。",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, increase(mysql_global_status_commands_total{instance=\"$host\"}[1h])>0)",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  },
  {
   "title": "MySQL 处理计数",
   "type": "graph",
   "description": "MySQL 处理统计是 MySQL 内部执行查询、修改、插入行和修改行、表和索引的内部统计信息。\n\n这是 MySQL 与存储引擎之间的层级。\n\n* `read_rnd_next` 是 MySQL 服务器在执行全表扫描的时候自增的指标，越高表明性能越差。\n* `read_key` 自增的时候则表明读取了一个索引。\n* `read_next` 是当存储引擎要求执行 'read the next index entry'的时候会被自增。该值越高则意味着要进行大量的索引扫描。",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_handlers_total{instance=\"$host\", handler!~\"commit|rollback|savepoint.*|prepare\"}[$interval]) or irate(mysql_global_status_handlers_total{instance=\"$host\", handler!~\"commit|rollback|savepoint.*|prepare\"}[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "MySQL 事务处理统计",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_handlers_total{instance=\"$host\", handler=~\"commit|rollback|savepoint.*|prepare\"}[$interval]) or irate(mysql_global_status_handlers_total{instance=\"$host\", handler=~\"commit|rollback|savepoint.*|prepare\"}[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  { "title": "文件与数据表", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "MySQL 读取文件统计",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_opened_files{instance=\"$host\"}[$interval]) or irate(mysql_global_status_opened_files{instance=\"$host\"}[5m])",
     "legendFormat": "正在打开的文件"
    }
   ]
  },
  {
   "title": "MySQL 打开的文件",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_open_files{instance=\"$host\"}",
     "legendFormat": "MySQL 打开的文件数"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_open_files_limit{instance=\"$host\"}",
     "legendFormat": "允许最大打开的文件数"
    },
    {
     "expr": "mysql_global_status_innodb_num_open_files{instance=\"$host\"}",
     "legendFormat": "InnoDB 打开的文件数"
    }
   ]
  },
  { "title": "Table Openings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "MySQL Table Open Cache Status",
   "type": "graph",
   "description": "**MySQL Table Open Cache Status**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_opened_tables{instance=\"$host\"}[$interval]) or irate(mysql_global_status_opened_tables{instance=\"$host\"}[5m])",
     "legendFormat": "Openings"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[5m])",
     "legendFormat": "Hits"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_misses{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_misses{instance=\"$host\"}[5m])",
     "legendFormat": "Misses"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_overflows{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_overflows{instance=\"$host\"}[5m])",
     "legendFormat": "Misses due to Overflows"
    },
    {
     "expr": "(rate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[5m]))/((rate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[5m]))+(rate(mysql_global_status_table_open_cache_misses{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_misses{instance=\"$host\"}[5m])))",
     "legendFormat": "Table Open Cache Hit Ratio"
    }
   ]
  },
  {
   "title": "MySQL Open Tables",
   "type": "graph",
   "description": "**MySQL Open Tables**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_open_tables{instance=\"$host\"}",
     "legendFormat": "Open Tables"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_table_open_cache{instance=\"$host\"}",
     "legendFormat": "Table Open Cache"
    }
   ]
  },
  { "title": "MySQL Table Definition Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "MySQL Table Definition Cache",
   "type": "graph",
   "description": "**MySQL Table Definition Cache**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_open_table_definitions{instance=\"$host\"}",
     "legendFormat": "Open Table Definitions"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_table_definition_cache{instance=\"$host\"}",
     "legendFormat": "Table Definitions Cache Size"
    },
    {
     "expr": "rate(mysql_global_status_opened_table_definitions{instance=\"$host\"}[$interval]) or irate(mysql_global_status_opened_table_definitions{instance=\"$host\"}[5m])",
     "legendFormat": "Opened Table Definitions"
    }
   ]
  }
 ]
}